version: '3.1'
services:
  mongodb:
    image: 'mongo:4.4.2'
    container_name: mongodb
    restart: always
    ports:
          - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./mongodb/volume:/data/db
      - ./mongodb/mongod.conf:/etc/mongod.conf
      - ./mongodb/log/:/var/log/mongodb/
    env_file:
      - .env
    command: ["-f", "/etc/mongod.conf"]

